import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.cwd()
const read = (relativePath) => readFileSync(join(root, relativePath), 'utf8')

const transcriptRoute = read('app/api/assets/[id]/transcript/route.ts')
assert.match(transcriptRoute, /export async function GET/)
assert.match(transcriptRoute, /export async function POST/)
assert.match(transcriptRoute, /export async function PATCH/)
assert.match(transcriptRoute, /assemblyTranscriptToSegments/)
assert.match(transcriptRoute, /startSourceAssetTranscription/)
assert.match(transcriptRoute, /status: 'transcribing'/)
assert.match(transcriptRoute, /transcript_segments/)

const syncRoute = read('app/api/assets/[id]/transcript/sync/route.ts')
assert.match(syncRoute, /getAssemblyAITranscriptionStatus/)
assert.match(syncRoute, /uploadTranscriptToR2/)
assert.match(syncRoute, /transcript_segments/)
assert.match(syncRoute, /let stage = 'resolve_request'/)
assert.match(syncRoute, /stage = 'poll_assemblyai'/)
assert.match(syncRoute, /stage = 'persist_transcript'/)
assert.match(syncRoute, /stage,/)

const helper = read('lib/server/source-transcript.ts')
assert.match(helper, /MAX_AUTO_TRANSCRIPT_DURATION_MS = 40 \* 60 \* 1000/)
assert.match(helper, /startsWith\('video\/'\)/)
assert.match(helper, /startAssemblyAITranscription/)
assert.match(helper, /transcript_job_id/)
assert.match(helper, /transcript_status: 'queued'/)

const assemblyApi = read('lib/api/assemblyai.ts')
assert.match(assemblyApi, /AbortSignal\.timeout/)

const normalizer = read('lib/r2/assembly-transcript.ts')
assert.match(normalizer, /assemblyTranscriptWords/)
assert.match(normalizer, /assemblyTranscriptToSegments/)
assert.match(normalizer, /group.length >= 12/)

const assetsRoute = read('app/api/projects/[id]/assets/route.ts')
assert.match(assetsRoute, /startSourceAssetTranscription/)
assert.match(assetsRoute, /transcriptDispatch/)
assert.doesNotMatch(assetsRoute, /dispatchModalSourceAnalysis/)

const editorPage = read('app/editor/[id]/page.tsx')
assert.match(editorPage, /api\/assets\/\$\{sourceAssetId\}\/transcript/)
assert.match(editorPage, /transcript\/sync/)
assert.match(editorPage, /method: 'PATCH'/)
assert.doesNotMatch(editorPage, /Fallback recovery for Dan Martell/)
assert.match(editorPage, /transcriptStartAttemptedRef/)
assert.match(editorPage, /!retry && transcriptStartAttemptedRef\.current === sourceAssetId/)
assert.match(editorPage, /api\/assets\/\$\{sourceAssetId\}\/transcript\?restart=1/)
assert.doesNotMatch(editorPage, /api\/prometheus-chat\/transcribe/)
assert.match(editorPage, /transcriptStatus: 'completed'/)
assert.match(editorPage, /TranscriptSegment/)

const proxy = read('lib/server/modal-backend-proxy.ts')
assert.match(proxy, /AbortSignal\.timeout/)
assert.match(proxy, /MODAL_PROXY_TIMEOUT_MS/)
assert.match(proxy, /MINI_RUN_BACKEND_URL/)
assert.match(proxy, /LANDSCAPE_BACKEND_URL/)
assert.match(proxy, /api\/pipeline\/render/)
assert.match(proxy, /api\\\/pipeline\\\/job/)
assert.match(proxy, /api\/runs/)
assert.doesNotMatch(proxy, /media\/\[A-Za-z0-9._~-\]+\$/)

const modalCore = read('lib/api/modal-core.ts')
assert.match(modalCore, /AbortSignal\.timeout/)
assert.match(modalCore, /DEFAULT_CLIENT_TIMEOUT_MS/)
assert.match(modalCore, /LANDSCAPE_RUN_CLIENT_TIMEOUT_MS/)
assert.match(modalCore, /api\/pipeline\/render/)
assert.match(modalCore, /api\/pipeline\/job/)
assert.match(modalCore, /getLandscapePage/)
assert.match(modalCore, /getManifest/)
assert.doesNotMatch(modalCore, /getMediaUrl/)
assert.doesNotMatch(modalCore, /dispatchSourceAnalysis/)
assert.doesNotMatch(modalCore, /\/media\//)

const landscapeRoute = read('app/api/landscape-backend/[...path]/route.ts')
assert.match(landscapeRoute, /LANDSCAPE_BACKEND_URL/)
assert.match(landscapeRoute, /'landscape'/)

const callParser = read('lib/pipeline/call-parser.ts')
assert.match(callParser, /classifyPipelineCall/)
assert.match(callParser, /durationSec <= 90/)
assert.match(callParser, /aspectRatio <= 1\.0/)
assert.match(callParser, /confidence: 1/)

const streamRoute = read('app/api/prometheus-chat/stream/route.ts')
assert.match(streamRoute, /sessionId: context\.sessionId/)
assert.match(streamRoute, /sessionId, reply, clientMessageId, streamJobs/)
assert.match(streamRoute, /jobs && jobs\.length/)

console.log('transcript + modal-safe-call pipeline checks passed')
