export interface CreatorVideoItem {
  id: string
  parentId?: string
  title: string
  subtitle: string
  description: string
  year: string
  runtime: string
  genre: string
  badge: string
  rating: number
  videoId: string
  image: string
  imagePosition?: string
  accent: string
  metaLine: string
  channelTitle: string
  views?: string
  isLocal: boolean
}

export const CREATOR_VIDEO_CATALOG: Record<string, CreatorVideoItem[]> = {
  'Alex Hormozi': [
    {
      id: 'alex_1',
      title: '$100M Leads: Behind the Scenes',
      subtitle: 'Launch film & playbook',
      description: 'Original behind-the-scenes documentary capturing the engineering, offers, and live event architecture of the $100M Leads release.',
      year: '2026',
      runtime: '12:59',
      genre: 'Documentary',
      badge: 'Official film',
      rating: 9.4,
      videoId: 'qel9bf653Es',
      image: '/library/alex-hormozi/behind-scenes.jpg',
      imagePosition: 'center',
      accent: '#55ff9b',
      metaLine: 'Official release | 12:59',
      channelTitle: 'Alex Hormozi',
      views: '1.4M views',
      isLocal: false,
    },
    {
      id: 'alex_2',
      title: 'The Offer Is King',
      subtitle: 'Grand slam strategy',
      description: 'Deep teardown on price-to-value discrepancy, value equations, and why product-market fit begins with offer packaging.',
      year: '2026',
      runtime: '13:44',
      genre: 'Offers',
      badge: 'Strategy breakdown',
      rating: 9.2,
      videoId: 'pxVeOkOVr2w',
      image: '/library/alex-hormozi/offers.jpg',
      imagePosition: 'center',
      accent: '#55ff9b',
      metaLine: 'Strategy masterclass | 13:44',
      channelTitle: 'Alex Hormozi',
      views: '980K views',
      isLocal: false,
    },
    {
      id: 'alex_3',
      title: 'My Best Sales Tactic',
      subtitle: 'High ticket closing',
      description: 'Psychology of objection handling, reducing perceived risk, and closing high-ticket clients without aggressive pressure.',
      year: '2026',
      runtime: '08:11',
      genre: 'Sales',
      badge: 'Tactical select',
      rating: 9.1,
      videoId: 'bx48qPlaGvE',
      image: '/library/alex-hormozi/sales.jpg',
      imagePosition: 'center',
      accent: '#55ff9b',
      metaLine: 'Sales clinic | 08:11',
      channelTitle: 'Alex Hormozi',
      views: '760K views',
      isLocal: false,
    },
    {
      id: 'alex_4',
      title: 'How to Stay Consistent',
      subtitle: 'Founder mindset',
      description: 'Why momentum is a lagging indicator of boring, unsexy discipline repeated over ten-year horizons.',
      year: '2025',
      runtime: '12:06',
      genre: 'Mindset',
      badge: 'Philosophy',
      rating: 9.3,
      videoId: 'WOZGZK7K-Jo',
      image: '/library/alex-hormozi/consistency.jpg',
      imagePosition: 'center',
      accent: '#55ff9b',
      metaLine: 'Mindset session | 12:06',
      channelTitle: 'Alex Hormozi',
      views: '1.1M views',
      isLocal: false,
    },
    {
      id: 'alex_5',
      title: 'The Big 4 Acquisition Models',
      subtitle: 'Stage keynote',
      description: 'Comprehensive stadium keynote breaking down cold outreach, paid advertising, content creation, and warm referrals.',
      year: '2025',
      runtime: '1:27:45',
      genre: 'Acquisition',
      badge: 'Feature keynote',
      rating: 9.6,
      videoId: 'XwZH-lOKG9c',
      image: '/library/alex-hormozi/keynote.jpg',
      imagePosition: 'center',
      accent: '#55ff9b',
      metaLine: 'Live keynote | 1:27:45',
      channelTitle: 'Alex Hormozi',
      views: '2.8M views',
      isLocal: false,
    },
    {
      id: 'alex_6',
      title: 'If I Started in 2026',
      subtitle: 'Modern playbook',
      description: 'How to build an eight-figure business from scratch in the age of AI, automated distribution, and media leverage.',
      year: '2026',
      runtime: '18:25',
      genre: 'Strategy',
      badge: 'Playbook',
      rating: 9.5,
      videoId: 'uWdIgftpvBI',
      image: '/library/alex-hormozi/business-2026.jpg',
      imagePosition: 'center',
      accent: '#55ff9b',
      metaLine: 'Future roadmap | 18:25',
      channelTitle: 'Alex Hormozi',
      views: '1.9M views',
      isLocal: false,
    },
  ],
  'Leila Hormozi': [
    {
      id: 'leila_1',
      title: 'How To Build A High Performing Team',
      subtitle: 'Organizational design',
      description: 'The exact framework Acquisition.com uses to recruit, interview, and align top-tier leadership talent.',
      year: '2026',
      runtime: '16:42',
      genre: 'Operations',
      badge: 'Leadership masterclass',
      rating: 9.3,
      videoId: 'TWuzAO7ukk0',
      image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 20%',
      accent: '#55ff9b',
      metaLine: 'Executive systems | 16:42',
      channelTitle: 'Leila Hormozi',
      views: '640K views',
      isLocal: false,
    },
    {
      id: 'leila_2',
      title: 'Scaling Past $50M As A Female CEO',
      subtitle: 'CEO leadership notes',
      description: 'Navigating executive pressure, operational complexity, and culture scaling across portfolio companies.',
      year: '2026',
      runtime: '21:15',
      genre: 'Scaling',
      badge: 'Executive interview',
      rating: 9.4,
      videoId: 'yvXNmdfYJYY',
      image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 18%',
      accent: '#55ff9b',
      metaLine: 'Executive interview | 21:15',
      channelTitle: 'Leila Hormozi',
      views: '510K views',
      isLocal: false,
    },
    {
      id: 'leila_3',
      title: 'The 3 Operational Rhythms',
      subtitle: 'Execution cadence',
      description: 'How to structure daily huddles, weekly sprints, and quarterly executive reviews without getting bogged down.',
      year: '2025',
      runtime: '14:08',
      genre: 'Management',
      badge: 'Operator protocol',
      rating: 9.1,
      videoId: 'wZeOwqmSw84',
      image: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 22%',
      accent: '#55ff9b',
      metaLine: 'Operations breakdown | 14:08',
      channelTitle: 'Leila Hormozi',
      views: '420K views',
      isLocal: false,
    },
    {
      id: 'leila_4',
      title: 'Hiring Signals & Interview Traps',
      subtitle: 'People ops select',
      description: 'How to spot high performers vs resume optimizers during 30-minute founder interviews.',
      year: '2025',
      runtime: '11:50',
      genre: 'People Ops',
      badge: 'Talent clinic',
      rating: 9.0,
      videoId: 'pxVeOkOVr2w',
      image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 16%',
      accent: '#55ff9b',
      metaLine: 'Talent selection | 11:50',
      channelTitle: 'Leila Hormozi',
      views: '380K views',
      isLocal: false,
    },
    {
      id: 'leila_5',
      title: 'Boardroom Decision Architecture',
      subtitle: 'Governance & strategy',
      description: 'Making irreversible strategic choices under uncertainty, market shifts, and capital constraints.',
      year: '2026',
      runtime: '19:30',
      genre: 'Strategy',
      badge: 'Boardroom notes',
      rating: 9.2,
      videoId: 'bx48qPlaGvE',
      image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 20%',
      accent: '#55ff9b',
      metaLine: 'Strategy session | 19:30',
      channelTitle: 'Leila Hormozi',
      views: '290K views',
      isLocal: false,
    },
    {
      id: 'leila_6',
      title: 'Discipline Over Motivation',
      subtitle: 'Mindset & resilience',
      description: 'The psychological stamina required to manage hundreds of employees while maintaining personal standards.',
      year: '2026',
      runtime: '13:12',
      genre: 'Growth',
      badge: 'Keynote',
      rating: 9.5,
      videoId: 'WOZGZK7K-Jo',
      image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 18%',
      accent: '#55ff9b',
      metaLine: 'Founder resilience | 13:12',
      channelTitle: 'Leila Hormozi',
      views: '710K views',
      isLocal: false,
    },
  ],
  'Codie Sanchez': [
    {
      id: 'codie_1',
      title: 'Boring Businesses That Print Cash',
      subtitle: 'Main street M&A',
      description: 'Why car washes, laundromats, and property management beat shiny venture-backed startups every time.',
      year: '2026',
      runtime: '15:20',
      genre: 'Business',
      badge: 'Cashflow playbook',
      rating: 9.3,
      videoId: 'YXYGSqaXVBg',
      image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 18%',
      accent: '#55ff9b',
      metaLine: 'Contrarian wealth | 15:20',
      channelTitle: 'Codie Sanchez',
      views: '1.2M views',
      isLocal: false,
    },
    {
      id: 'codie_2',
      title: 'How To Buy A Business With $0 Down',
      subtitle: 'Deal structuring clinic',
      description: 'Seller financing, SBA loan stacking, and earnouts: the exact negotiation script for buying profitable assets.',
      year: '2026',
      runtime: '18:45',
      genre: 'Finance',
      badge: 'Deal room',
      rating: 9.5,
      videoId: '_R_ZxI0hrs4',
      image: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 20%',
      accent: '#55ff9b',
      metaLine: 'Deal room session | 18:45',
      channelTitle: 'Codie Sanchez',
      views: '940K views',
      isLocal: false,
    },
    {
      id: 'codie_3',
      title: 'The Micro-Private-Equity Model',
      subtitle: 'Portfolio strategy',
      description: 'How to build a holding company of service businesses and hire general managers to run operations.',
      year: '2025',
      runtime: '14:10',
      genre: 'Investing',
      badge: 'Holding company',
      rating: 9.1,
      videoId: 'Wfij1Dxn9UQ',
      image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 18%',
      accent: '#55ff9b',
      metaLine: 'Portfolio architecture | 14:10',
      channelTitle: 'Codie Sanchez',
      views: '620K views',
      isLocal: false,
    },
    {
      id: 'codie_4',
      title: 'Due Diligence Red Flags',
      subtitle: 'M&A auditing',
      description: 'Reviewing profit and loss statements, hidden tax liabilities, and customer concentration risks before wire day.',
      year: '2025',
      runtime: '11:34',
      genre: 'Finance',
      badge: 'Due diligence',
      rating: 9.0,
      videoId: 'oapvt-AaFpc',
      image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 22%',
      accent: '#55ff9b',
      metaLine: 'Risk audit | 11:34',
      channelTitle: 'Codie Sanchez',
      views: '480K views',
      isLocal: false,
    },
    {
      id: 'codie_5',
      title: 'The Contrarian Wealth Blueprint',
      subtitle: 'Keynote address',
      description: 'Escaping the paycheck treadmill by owning tangible cashflow-producing assets that withstand market downturns.',
      year: '2026',
      runtime: '24:18',
      genre: 'Wealth',
      badge: 'Keynote',
      rating: 9.4,
      videoId: '5BgmmGHYk1U',
      image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 18%',
      accent: '#55ff9b',
      metaLine: 'Keynote masterclass | 24:18',
      channelTitle: 'Codie Sanchez',
      views: '1.5M views',
      isLocal: false,
    },
    {
      id: 'codie_6',
      title: 'Operator Wealth & Capital Allocation',
      subtitle: 'Executive roundtable',
      description: 'Where smart business owners reinvest operating cashflow to build multi-generational security.',
      year: '2026',
      runtime: '16:02',
      genre: 'Strategy',
      badge: 'Capital allocation',
      rating: 9.2,
      videoId: 'pLxRBCBY1HQ',
      image: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 16%',
      accent: '#55ff9b',
      metaLine: 'Capital strategy | 16:02',
      channelTitle: 'Codie Sanchez',
      views: '530K views',
      isLocal: false,
    },
  ],
  'Dan Martell': [
    {
      id: 'dan_1',
      title: 'Buy Back Your Time: The 10-80-10 Rule',
      subtitle: 'Calendar architecture',
      description: 'How high-performance founders delegate the 80% middle of tasks while controlling the initial 10% and final 10%.',
      year: '2026',
      runtime: '17:35',
      genre: 'Productivity',
      badge: 'Flagship method',
      rating: 9.5,
      videoId: 'TWuzAO7ukk0',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 18%',
      accent: '#55ff9b',
      metaLine: 'Calendar mastery | 17:35',
      channelTitle: 'Dan Martell',
      views: '880K views',
      isLocal: false,
    },
    {
      id: 'dan_2',
      title: 'How To Scale SaaS From $1M to $10M ARR',
      subtitle: 'Software playbook',
      description: 'Product-led growth, sales-assisted conversions, and churn mitigation frameworks for venture & bootstrapped SaaS.',
      year: '2026',
      runtime: '22:40',
      genre: 'SaaS',
      badge: 'Growth clinic',
      rating: 9.4,
      videoId: 'yvXNmdfYJYY',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 20%',
      accent: '#55ff9b',
      metaLine: 'SaaS playbook | 22:40',
      channelTitle: 'Dan Martell',
      views: '410K views',
      isLocal: false,
    },
    {
      id: 'dan_3',
      title: 'The Executive Assistant Replacement Ladder',
      subtitle: 'Delegation systems',
      description: 'Hiring, training, and empowering an executive assistant to handle inbox, calendar, and operational logistics.',
      year: '2025',
      runtime: '13:50',
      genre: 'Operations',
      badge: 'Systems masterclass',
      rating: 9.2,
      videoId: 'wZeOwqmSw84',
      image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 16%',
      accent: '#55ff9b',
      metaLine: 'Delegation system | 13:50',
      channelTitle: 'Dan Martell',
      views: '520K views',
      isLocal: false,
    },
    {
      id: 'dan_4',
      title: 'Building Companies To Exit',
      subtitle: 'M&A valuation',
      description: 'How to structure contracts, intellectual property, and management so strategic buyers pay top multiples.',
      year: '2025',
      runtime: '19:12',
      genre: 'Scaling',
      badge: 'Exit strategy',
      rating: 9.1,
      videoId: 'qel9bf653Es',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 18%',
      accent: '#55ff9b',
      metaLine: 'Exit roadmap | 19:12',
      channelTitle: 'Dan Martell',
      views: '340K views',
      isLocal: false,
    },
    {
      id: 'dan_5',
      title: 'Boardroom Focus & Leadership Cadence',
      subtitle: 'Executive coaching',
      description: 'Leading senior executives when they possess more functional domain expertise than the founder.',
      year: '2026',
      runtime: '15:04',
      genre: 'Leadership',
      badge: 'Leadership',
      rating: 9.0,
      videoId: 'pxVeOkOVr2w',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 20%',
      accent: '#55ff9b',
      metaLine: 'Executive focus | 15:04',
      channelTitle: 'Dan Martell',
      views: '290K views',
      isLocal: false,
    },
    {
      id: 'dan_6',
      title: 'Capital Efficiency & Zero-Waste Growth',
      subtitle: 'Financial discipline',
      description: 'Surviving market downturns by keeping burn low, gross margins above 80%, and payback under 12 months.',
      year: '2026',
      runtime: '14:28',
      genre: 'Business',
      badge: 'Capital strategy',
      rating: 9.3,
      videoId: 'bx48qPlaGvE',
      image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 16%',
      accent: '#55ff9b',
      metaLine: 'Capital growth | 14:28',
      channelTitle: 'Dan Martell',
      views: '450K views',
      isLocal: false,
    },
  ],
  'Dean Graziosi': [
    {
      id: 'dean_1',
      title: 'Millionaire Success Habits Workshop',
      subtitle: 'Mindset principles',
      description: 'The foundational morning rituals, mental models, and energy triggers used by high-performance entrepreneurs.',
      year: '2026',
      runtime: '21:05',
      genre: 'Mindset',
      badge: 'Workshop feature',
      rating: 9.4,
      videoId: 'YXYGSqaXVBg',
      image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 20%',
      accent: '#55ff9b',
      metaLine: 'Mindset workshop | 21:05',
      channelTitle: 'Dean Graziosi',
      views: '920K views',
      isLocal: false,
    },
    {
      id: 'dean_2',
      title: 'The Art Of High-Converting Persuasion',
      subtitle: 'Communication mastery',
      description: 'Storytelling frameworks that connect deeply with audiences on live stages, virtual webinars, and video.',
      year: '2026',
      runtime: '18:50',
      genre: 'Speaking',
      badge: 'Stage clinic',
      rating: 9.3,
      videoId: '_R_ZxI0hrs4',
      image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 18%',
      accent: '#55ff9b',
      metaLine: 'Stage mastery | 18:50',
      channelTitle: 'Dean Graziosi',
      views: '670K views',
      isLocal: false,
    },
    {
      id: 'dean_3',
      title: 'Turning Knowledge Into Digital Products',
      subtitle: 'Knowledge industry',
      description: 'Packaging domain expertise, workshops, and coaching into digital assets with recurring momentum.',
      year: '2025',
      runtime: '16:30',
      genre: 'Education',
      badge: 'Digital assets',
      rating: 9.1,
      videoId: 'Wfij1Dxn9UQ',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 22%',
      accent: '#55ff9b',
      metaLine: 'Digital curriculum | 16:30',
      channelTitle: 'Dean Graziosi',
      views: '540K views',
      isLocal: false,
    },
    {
      id: 'dean_4',
      title: 'Reframing Failure Into Competitive Advantage',
      subtitle: 'Mental toughness',
      description: 'How setbacks and lost deals reveal blind spots and build the fortitude necessary for long-term victory.',
      year: '2025',
      runtime: '12:44',
      genre: 'Coaching',
      badge: 'Perspective',
      rating: 9.0,
      videoId: 'oapvt-AaFpc',
      image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 18%',
      accent: '#55ff9b',
      metaLine: 'Resilience coaching | 12:44',
      channelTitle: 'Dean Graziosi',
      views: '380K views',
      isLocal: false,
    },
    {
      id: 'dean_5',
      title: 'Live Launch Confidence & Stage Energy',
      subtitle: 'Event execution',
      description: 'Maintaining peak physical state and commanding audience attention throughout multi-day virtual summits.',
      year: '2026',
      runtime: '15:15',
      genre: 'Sales',
      badge: 'Launch select',
      rating: 9.2,
      videoId: '5BgmmGHYk1U',
      image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 16%',
      accent: '#55ff9b',
      metaLine: 'Live launch | 15:15',
      channelTitle: 'Dean Graziosi',
      views: '490K views',
      isLocal: false,
    },
    {
      id: 'dean_6',
      title: 'The Discipline Of Daily Momentum',
      subtitle: 'Peak performance',
      description: 'Eliminating decision fatigue, protecting focus hours, and engineering an environment designed for winning.',
      year: '2026',
      runtime: '14:20',
      genre: 'Motivation',
      badge: 'Keynote',
      rating: 9.5,
      videoId: 'pLxRBCBY1HQ',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 20%',
      accent: '#55ff9b',
      metaLine: 'Daily protocol | 14:20',
      channelTitle: 'Dean Graziosi',
      views: '730K views',
      isLocal: false,
    },
  ],
  'Iman Gadzhi': [
    {
      id: 'iman_1',
      title: 'How To Scale An Agency In 2026',
      subtitle: 'Modern agency blueprint',
      description: 'The exact shift from commoditized services to performance-driven, high-ticket growth partnerships.',
      year: '2026',
      runtime: '19:40',
      genre: 'Agency',
      badge: 'Agency masterclass',
      rating: 9.5,
      videoId: 'oapvt-AaFpc',
      image: '/style-previews/iman-1.jpg',
      imagePosition: '50% 18%',
      accent: '#55ff9b',
      metaLine: 'Agency roadmap | 19:40',
      channelTitle: 'Iman Gadzhi',
      views: '1.8M views',
      isLocal: false,
    },
    {
      id: 'iman_2',
      title: 'The Monk Mode Protocol: Full Guide',
      subtitle: 'Hyperfocus blueprint',
      description: 'The strict non-negotiable isolation rules that maximize cognitive output and produce career-defining milestones.',
      year: '2026',
      runtime: '24:12',
      genre: 'Mindset',
      badge: 'Focus protocol',
      rating: 9.7,
      videoId: '5BgmmGHYk1U',
      image: '/style-previews/iman-2.jpg',
      imagePosition: '50% 18%',
      accent: '#55ff9b',
      metaLine: 'Hyperfocus system | 24:12',
      channelTitle: 'Iman Gadzhi',
      views: '3.1M views',
      isLocal: false,
    },
    {
      id: 'iman_3',
      title: 'Signing $5,000/mo Retainer Clients',
      subtitle: 'Client acquisition',
      description: 'Loom video audits, warm referrals, and bespoke offer positioning that commands premier corporate retainers.',
      year: '2025',
      runtime: '16:05',
      genre: 'Sales',
      badge: 'Acquisition',
      rating: 9.2,
      videoId: 'pLxRBCBY1HQ',
      image: '/style-previews/dark-cinematic-1.jpg',
      imagePosition: '50% 20%',
      accent: '#55ff9b',
      metaLine: 'High-ticket sales | 16:05',
      channelTitle: 'Iman Gadzhi',
      views: '890K views',
      isLocal: false,
    },
    {
      id: 'iman_4',
      title: 'Direct-To-Camera Visual Authority',
      subtitle: 'Cinematic brand framing',
      description: 'Color science, camera focal lengths, and deliberate vocal cadence that establish immediate marketplace gravity.',
      year: '2025',
      runtime: '13:18',
      genre: 'Brand',
      badge: 'Visual identity',
      rating: 9.3,
      videoId: 'qel9bf653Es',
      image: '/style-previews/docs-story-1.jpg',
      imagePosition: '50% 18%',
      accent: '#55ff9b',
      metaLine: 'Visual authority | 13:18',
      channelTitle: 'Iman Gadzhi',
      views: '740K views',
      isLocal: false,
    },
    {
      id: 'iman_5',
      title: 'Luxury Branding & Aesthetic Motion',
      subtitle: 'Creative direction',
      description: 'Designing marketing assets, title sequences, and editing treatments that signal uncompromising high caliber.',
      year: '2026',
      runtime: '15:22',
      genre: 'Aesthetic',
      badge: 'Creative direction',
      rating: 9.4,
      videoId: 'pxVeOkOVr2w',
      image: '/style-previews/reels-heat-1.webp',
      imagePosition: '50% 16%',
      accent: '#55ff9b',
      metaLine: 'Luxury creative | 15:22',
      channelTitle: 'Iman Gadzhi',
      views: '1.2M views',
      isLocal: false,
    },
    {
      id: 'iman_6',
      title: 'High-Net-Worth Operator Discipline',
      subtitle: 'Capital & freedom',
      description: 'How top young founders reinvest profits, protect personal time, and build asset diversification.',
      year: '2026',
      runtime: '17:45',
      genre: 'Wealth',
      badge: 'Keynote',
      rating: 9.6,
      videoId: 'WOZGZK7K-Jo',
      image: '/style-previews/podcast-1.jpg',
      imagePosition: '50% 20%',
      accent: '#55ff9b',
      metaLine: 'Wealth mindset | 17:45',
      channelTitle: 'Iman Gadzhi',
      views: '1.6M views',
      isLocal: false,
    },
  ],
  'Ray Dalio': [
    {
      id: 'ray_1',
      title: 'How The Economic Machine Works In 30 Minutes',
      subtitle: 'Macro foundations',
      description: 'Ray Dalio’s legendary animation detailing short-term debt cycles, long-term deleveraging, and central bank mechanics.',
      year: '2026',
      runtime: '31:00',
      genre: 'Macro',
      badge: 'All-time classic',
      rating: 9.9,
      videoId: 'PHe0bXAIuk0',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 16%',
      accent: '#55ff9b',
      metaLine: 'Macroeconomics | 31:00',
      channelTitle: 'Principles by Ray Dalio',
      views: '44M views',
      isLocal: false,
    },
    {
      id: 'ray_2',
      title: 'Principles For The Changing World Order',
      subtitle: 'Empire cycles',
      description: 'Historical 500-year patterns of currency debasement, internal conflicts, and geopolitical shifts.',
      year: '2026',
      runtime: '43:38',
      genre: 'History',
      badge: 'Global macro',
      rating: 9.8,
      videoId: 'Nu4lHaSh7D4',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 18%',
      accent: '#55ff9b',
      metaLine: 'World order analysis | 43:38',
      channelTitle: 'Principles by Ray Dalio',
      views: '18M views',
      isLocal: false,
    },
    {
      id: 'ray_3',
      title: 'The All-Weather Portfolio & Risk Parity',
      subtitle: 'Asset allocation',
      description: 'Balancing equities, commodities, and fixed income to preserve capital regardless of growth or inflation regimes.',
      year: '2025',
      runtime: '18:14',
      genre: 'Investing',
      badge: 'Portfolio theory',
      rating: 9.5,
      videoId: 'rFV7wdEX-Mo',
      image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 20%',
      accent: '#55ff9b',
      metaLine: 'Portfolio framework | 18:14',
      channelTitle: 'Principles by Ray Dalio',
      views: '2.1M views',
      isLocal: false,
    },
    {
      id: 'ray_4',
      title: 'Radical Transparency In High-Stakes Teams',
      subtitle: 'Bridgewater culture',
      description: 'Dot collector systems, believability-weighted decision making, and removing ego from strategic disputes.',
      year: '2025',
      runtime: '15:40',
      genre: 'Principles',
      badge: 'Management protocol',
      rating: 9.4,
      videoId: 'qel9bf653Es',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 16%',
      accent: '#55ff9b',
      metaLine: 'Organizational culture | 15:40',
      channelTitle: 'Principles by Ray Dalio',
      views: '1.3M views',
      isLocal: false,
    },
    {
      id: 'ray_5',
      title: 'The Next Great Deleveraging',
      subtitle: 'Debt cycle briefing',
      description: 'Navigating debt-to-GDP extremes, inflation spikes, and asset repricing in modern financial markets.',
      year: '2026',
      runtime: '21:50',
      genre: 'Finance',
      badge: 'Market briefing',
      rating: 9.3,
      videoId: 'XwZH-lOKG9c',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 18%',
      accent: '#55ff9b',
      metaLine: 'Market briefing | 21:50',
      channelTitle: 'Principles by Ray Dalio',
      views: '980K views',
      isLocal: false,
    },
    {
      id: 'ray_6',
      title: 'Fail Well: The Evolutionary Formula',
      subtitle: 'Life principles',
      description: 'Pain + Reflection = Progress. The biological reality that struggle is the required precursor to strength.',
      year: '2026',
      runtime: '14:10',
      genre: 'Philosophy',
      badge: 'Life principles',
      rating: 9.6,
      videoId: 'WOZGZK7K-Jo',
      image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&auto=format&fit=crop&q=80',
      imagePosition: '50% 16%',
      accent: '#55ff9b',
      metaLine: 'Evolutionary formula | 14:10',
      channelTitle: 'Principles by Ray Dalio',
      views: '1.7M views',
      isLocal: false,
    },
  ],
}

export function getCreatorVideos(creatorName: string): CreatorVideoItem[] {
  return CREATOR_VIDEO_CATALOG[creatorName] ?? CREATOR_VIDEO_CATALOG['Alex Hormozi']
}
