import type { StudioReferenceCategory } from './studio-references'

const REFERENCE_CUE = 'Borrow the reference’s composition, subject scale, color contrast, and text hierarchy while creating original artwork for the selected video.'

export const KALLAWAY_STUDIO_REFERENCES: Array<{
  id: string
  name: string
  src: string
  category: StudioReferenceCategory
  cue: string
}> = [
  { id: "kallaway-vmsdhy9itli", name: "The ‘Invisible’ Hook That Makes Your Videos Impossible to Skip (Subliminal Influence)", src: "/thumbnail-references/kallaway/vmsdhy9itli.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-s-7vkwsu0gs", name: "If I only had 90 days to build a personal brand, I’d do this", src: "/thumbnail-references/kallaway/s-7vkwsu0gs.webp", category: "Creator Business", cue: REFERENCE_CUE },
  { id: "kallaway-94ezzmypzls", name: "I Reversed Engineered Social Media Algorithms", src: "/thumbnail-references/kallaway/94ezzmypzls.webp", category: "AI & Tools", cue: REFERENCE_CUE },
  { id: "kallaway-w--te9w_n_a", name: "How to Become A Master Storyteller (It'll Blow Up Your Business)", src: "/thumbnail-references/kallaway/w--te9w_n_a.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-sj0otnuuzls", name: "The BEST & WORST Advice for Growing on Social Media", src: "/thumbnail-references/kallaway/sj0otnuuzls.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-vwlk6mbdato", name: "How to Use Claude To Grow From 0 to 100K Followers (Full Course)", src: "/thumbnail-references/kallaway/vwlk6mbdato.webp", category: "AI & Tools", cue: REFERENCE_CUE },
  { id: "kallaway-tneyzxihwno", name: "I Blew Up On Social Media in 100 Days to Prove It's Not Luck (Again)", src: "/thumbnail-references/kallaway/tneyzxihwno.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-1ilmgcxjbqy", name: "The NEW Personal Brand Strategy Dominating Social Media in 2026", src: "/thumbnail-references/kallaway/1ilmgcxjbqy.webp", category: "Creator Business", cue: REFERENCE_CUE },
  { id: "kallaway-pniyikmysyw", name: "The Psychology of Killer Hooks", src: "/thumbnail-references/kallaway/pniyikmysyw.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-fvsl4zkcpik", name: "Everything I Learned Growing From 0 to 2M+ Followers in 3 Years", src: "/thumbnail-references/kallaway/fvsl4zkcpik.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-wkdeldemxr0", name: "The Art of Personal Branding", src: "/thumbnail-references/kallaway/wkdeldemxr0.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-cnk9nq8jpcs", name: "5 Claude Skills To Grow Faster Than 99% of People on Social Media", src: "/thumbnail-references/kallaway/cnk9nq8jpcs.webp", category: "AI & Tools", cue: REFERENCE_CUE },
  { id: "kallaway-cerzvxo8kf8", name: "The NEW Rules of Social Media in the Age of AI", src: "/thumbnail-references/kallaway/cerzvxo8kf8.webp", category: "AI & Tools", cue: REFERENCE_CUE },
  { id: "kallaway-psiy9ngezc8", name: "The ONLY 4 Things You Need to Make Sales from EVERY Video", src: "/thumbnail-references/kallaway/psiy9ngezc8.webp", category: "Creator Business", cue: REFERENCE_CUE },
  { id: "kallaway-lvuonlyrs7g", name: "How to Make ANY Topic Addictive on Social Media (The Illusion of Novelty)", src: "/thumbnail-references/kallaway/lvuonlyrs7g.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-6g1widxwf5w", name: "BY FAR, The Smartest Way to Build A Personal Brand in 2026", src: "/thumbnail-references/kallaway/6g1widxwf5w.webp", category: "Creator Business", cue: REFERENCE_CUE },
  { id: "kallaway-a7vjpiqq8xk", name: "How To Create Irresistible Hooks With Claude (and blow up your content)", src: "/thumbnail-references/kallaway/a7vjpiqq8xk.webp", category: "AI & Tools", cue: REFERENCE_CUE },
  { id: "kallaway-dfsu-yprts8", name: "The BIGGEST Lies You’ve Been Told About Social Media", src: "/thumbnail-references/kallaway/dfsu-yprts8.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-46t_cn0lx2e", name: "The NEW Era of Personal Brands is Here (and you’re not ready)", src: "/thumbnail-references/kallaway/46t_cn0lx2e.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-b9l9trhu5vw", name: "Copy This System, It’ll Blow Up Your Social Media", src: "/thumbnail-references/kallaway/b9l9trhu5vw.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-imzontrgvfg", name: "The NEW Way to WIN on Social Media in 2026", src: "/thumbnail-references/kallaway/imzontrgvfg.webp", category: "Platform Trends", cue: REFERENCE_CUE },
  { id: "kallaway-kyc8r-zitve", name: "The Neuroscience of Addictive Storytelling (And How to Master It)", src: "/thumbnail-references/kallaway/kyc8r-zitve.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-cuvytmbozjk", name: "How to Build an Audience That's Obsessed With You (The Power of Suggestion)", src: "/thumbnail-references/kallaway/cuvytmbozjk.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-bqzd0h0gmu0", name: "How ‘Regular’ People Are Making Millions From Social Media", src: "/thumbnail-references/kallaway/bqzd0h0gmu0.webp", category: "Creator Business", cue: REFERENCE_CUE },
  { id: "kallaway-8cqidxgtgmu", name: "How Social Media Algorithms Actually Work (And How to Beat Them)", src: "/thumbnail-references/kallaway/8cqidxgtgmu.webp", category: "AI & Tools", cue: REFERENCE_CUE },
  { id: "kallaway-zm3elcbe48i", name: "Speaking Like This Gives You an Unfair Advantage on Social Media", src: "/thumbnail-references/kallaway/zm3elcbe48i.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-xw_hhw1v1a8", name: "How To Build a Personal Brand That’s Magnetic As F_ck", src: "/thumbnail-references/kallaway/xw_hhw1v1a8.webp", category: "Creator Business", cue: REFERENCE_CUE },
  { id: "kallaway-lf7zxu4wius", name: "How to Get Rich on Social Media (Without Luck, Time, or Being a Genius)", src: "/thumbnail-references/kallaway/lf7zxu4wius.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-pcnrzbwovuk", name: "Say This in Your Videos, It’ll Improve Your Storytelling by 10x", src: "/thumbnail-references/kallaway/pcnrzbwovuk.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-8vollwmcluy", name: "Copy This Hook, It'll Blow Up Your Social Media", src: "/thumbnail-references/kallaway/8vollwmcluy.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-o_n5ed5fe1i", name: "If I Started Social Media From Scratch in 2026, I’d Do This", src: "/thumbnail-references/kallaway/o_n5ed5fe1i.webp", category: "Platform Trends", cue: REFERENCE_CUE },
  { id: "kallaway-dsdniug5eh4", name: "AI is About to Change Social Media Forever. Be Prepared.", src: "/thumbnail-references/kallaway/dsdniug5eh4.webp", category: "AI & Tools", cue: REFERENCE_CUE },
  { id: "kallaway-z8j3pups5gc", name: "How I Grew from 0 to 250,000 Subscribers in 1 Year (Nobody Teaches This)", src: "/thumbnail-references/kallaway/z8j3pups5gc.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-ps2mi1iqi-c", name: "6 Social Media Trends That Will Define 2026", src: "/thumbnail-references/kallaway/ps2mi1iqi-c.webp", category: "Platform Trends", cue: REFERENCE_CUE },
  { id: "kallaway-i7uprl4h1fm", name: "Give me 18 minutes, and I’ll improve your video by 193%", src: "/thumbnail-references/kallaway/i7uprl4h1fm.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-onqoydxwxda", name: "How to Create a Killer Hook (Impossible to Skip)", src: "/thumbnail-references/kallaway/onqoydxwxda.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-vx-inqa3mkk", name: "The Future Of Social Media Is Here", src: "/thumbnail-references/kallaway/vx-inqa3mkk.webp", category: "Platform Trends", cue: REFERENCE_CUE },
  { id: "kallaway-fk6lexgmpxi", name: "How to Speedrun Social Media", src: "/thumbnail-references/kallaway/fk6lexgmpxi.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-sdhkqbkc7ga", name: "Storytelling Is Easier Than You Think", src: "/thumbnail-references/kallaway/sdhkqbkc7ga.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-jtmstmt4wlc", name: "How to Become a Storytelling Genius (Dopamine Ladders)", src: "/thumbnail-references/kallaway/jtmstmt4wlc.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-1q__vs2jqbi", name: "How to Create Any Content 10x Faster With AI", src: "/thumbnail-references/kallaway/1q__vs2jqbi.webp", category: "AI & Tools", cue: REFERENCE_CUE },
  { id: "kallaway-7pcesr-0kiw", name: "If You Don't Understand Psychology, You Don't Understand Social Media", src: "/thumbnail-references/kallaway/7pcesr-0kiw.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-tvzos5z019u", name: "I Studied 10,000+ Videos, These Mistakes Are Killing Your Content", src: "/thumbnail-references/kallaway/tvzos5z019u.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-jzcupmaomae", name: "Why The Smartest Creators I Know Focus on Packaging, Not Content", src: "/thumbnail-references/kallaway/jzcupmaomae.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-acejrhzbsvk", name: "Everything you know about content is (probably) wrong", src: "/thumbnail-references/kallaway/acejrhzbsvk.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-xxzv82gnolg", name: "You’re Not Ready for the Next Phase of Social Media", src: "/thumbnail-references/kallaway/xxzv82gnolg.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-s9flxfv9dxg", name: "The ONLY 6 Words You Need to Hook ANY Viewer", src: "/thumbnail-references/kallaway/s9flxfv9dxg.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-snuzdt3eppg", name: "How to WIN on Social Media as a Business Owner in 2026 (Nobody Teaches this)", src: "/thumbnail-references/kallaway/snuzdt3eppg.webp", category: "Creator Business", cue: REFERENCE_CUE },
  { id: "kallaway-caeygdsnt9m", name: "6 Content Mistakes That Are KILLING Small Creators (Nobody Teaches This)", src: "/thumbnail-references/kallaway/caeygdsnt9m.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-_z11mjfh2zy", name: "How to Script Viral Videos 10x Faster (Nobody Teaches This)", src: "/thumbnail-references/kallaway/_z11mjfh2zy.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-pirngdczd3y", name: "The Science-Based Method To Create Irresistible Ideas", src: "/thumbnail-references/kallaway/pirngdczd3y.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-_60qfnsymcs", name: "This Video Will Change How You View Social Media", src: "/thumbnail-references/kallaway/_60qfnsymcs.webp", category: "Platform Trends", cue: REFERENCE_CUE },
  { id: "kallaway-o2np0lfisso", name: "Game Theory Is The Cheat Code to Social Media", src: "/thumbnail-references/kallaway/o2np0lfisso.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-auptvaoibgk", name: "How to Build a Cult-Like Personal Brand on Social Media", src: "/thumbnail-references/kallaway/auptvaoibgk.webp", category: "Creator Business", cue: REFERENCE_CUE },
  { id: "kallaway-0f6_praijji", name: "How to write a script so good viewers can’t stop watching", src: "/thumbnail-references/kallaway/0f6_praijji.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-askd_ypxnbw", name: "Social Media Is Evolving", src: "/thumbnail-references/kallaway/askd_ypxnbw.webp", category: "Platform Trends", cue: REFERENCE_CUE },
  { id: "kallaway-mbx4w5g0bps", name: "The Easiest Way to Make Viral Content (For ANY Business)", src: "/thumbnail-references/kallaway/mbx4w5g0bps.webp", category: "Creator Business", cue: REFERENCE_CUE },
  { id: "kallaway-vb-2ezx_b0m", name: "The ‘Viral’ Trap, Explained", src: "/thumbnail-references/kallaway/vb-2ezx_b0m.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-mp0eexujhhs", name: "I Failed at Social Media, Until I Understood This", src: "/thumbnail-references/kallaway/mp0eexujhhs.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-2bypp_9f0-q", name: "Give me 15 mins, and I'll make your hooks impossible to skip", src: "/thumbnail-references/kallaway/2bypp_9f0-q.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-vcqgw5zwtdq", name: "Social Media Is About to Change Forever (and nobody even realises)", src: "/thumbnail-references/kallaway/vcqgw5zwtdq.webp", category: "Platform Trends", cue: REFERENCE_CUE },
  { id: "kallaway-xz0h6ta9f6a", name: "It took me 1,000+ hours to learn this about content, but I’ll teach you in 31 minutes", src: "/thumbnail-references/kallaway/xz0h6ta9f6a.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-_spyh8wta-4", name: "I Tested 100+ AI Tools, These 9 Will Blow Up Your Content", src: "/thumbnail-references/kallaway/_spyh8wta-4.webp", category: "AI & Tools", cue: REFERENCE_CUE },
  { id: "kallaway-vit-_sjcs5i", name: "Brutally Honest Truths That Give You an Unfair Advantage on Social Media", src: "/thumbnail-references/kallaway/vit-_sjcs5i.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-bjiqj-fxfpw", name: "Social Media Has an AI Problem", src: "/thumbnail-references/kallaway/bjiqj-fxfpw.webp", category: "AI & Tools", cue: REFERENCE_CUE },
  { id: "kallaway-iqy644uooqm", name: "How to Create Irresistible Thumbnails (and blow up your content)", src: "/thumbnail-references/kallaway/iqy644uooqm.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-8clpw1wgj5g", name: "How to Reprogram Your Brain to Stop Overthinking", src: "/thumbnail-references/kallaway/8clpw1wgj5g.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-u7sb-gidbqw", name: "44 Tricks To Instantly Get More Views on Social Media", src: "/thumbnail-references/kallaway/u7sb-gidbqw.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-oryfj_yxz6m", name: "How to Build an Audience of Buyers (Not just empty views)", src: "/thumbnail-references/kallaway/oryfj_yxz6m.webp", category: "Creator Business", cue: REFERENCE_CUE },
  { id: "kallaway-h_yqswsxwhy", name: "Social Media Isn’t Hard. It’s Misunderstood.", src: "/thumbnail-references/kallaway/h_yqswsxwhy.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-9k1b6dsdc50", name: "6 Levels of Storytelling Every Creator MUST Master", src: "/thumbnail-references/kallaway/9k1b6dsdc50.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-yd2vbag4x8y", name: "Why Your Content Isn’t Getting Views (and how to fix it)", src: "/thumbnail-references/kallaway/yd2vbag4x8y.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-96hqjrqa_s4", name: "Storytelling Tactics Top Creators Use To Hook You", src: "/thumbnail-references/kallaway/96hqjrqa_s4.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-3y-wiiuaqb4", name: "How I Grew from 0 to 100K Subscribers in 5 Months (Nobody Teaches This)", src: "/thumbnail-references/kallaway/3y-wiiuaqb4.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-xnoe8aa9pmw", name: "I Studied 100 Viral Hooks, These 6 Will Make You Go Viral", src: "/thumbnail-references/kallaway/xnoe8aa9pmw.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-_gpsfzovvc4", name: "How to Blow Up on Social Media (even if you don’t have time)", src: "/thumbnail-references/kallaway/_gpsfzovvc4.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-p4w23v_llve", name: "How to Make Addictive Videos (and blow up your social media)", src: "/thumbnail-references/kallaway/p4w23v_llve.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-v923wjdhsca", name: "How to ACTUALLY Grow on Social Media in 2025 (Evidence-Based)", src: "/thumbnail-references/kallaway/v923wjdhsca.webp", category: "Platform Trends", cue: REFERENCE_CUE },
  { id: "kallaway-7i50pecz7su", name: "How To Write A Killer Script That Keeps Viewers Hooked", src: "/thumbnail-references/kallaway/7i50pecz7su.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-35spfdc1exy", name: "How to Master the Art of Speaking (and blow up your content)", src: "/thumbnail-references/kallaway/35spfdc1exy.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-wgxgimzvda4", name: "7 Storytelling Mistakes That Are KILLING Small Creators", src: "/thumbnail-references/kallaway/wgxgimzvda4.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-sccu6eky8iq", name: "Social Media Is A Video Game (Here Are The Cheat Codes)", src: "/thumbnail-references/kallaway/sccu6eky8iq.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-g_6tiu7zhdw", name: "18 Psychology Tricks to Get Viewers Addicted to Your Videos", src: "/thumbnail-references/kallaway/g_6tiu7zhdw.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-yqec4sxbqp4", name: "Stop Playing Social Media on ‘Hard Mode’ (6 Cheat Codes to Win in 2025)", src: "/thumbnail-references/kallaway/yqec4sxbqp4.webp", category: "Platform Trends", cue: REFERENCE_CUE },
  { id: "kallaway-urr7yqz6ida", name: "What I Learned After 1 Year Of Being A Full-Time Creator", src: "/thumbnail-references/kallaway/urr7yqz6ida.webp", category: "Creator Business", cue: REFERENCE_CUE },
  { id: "kallaway-onqul-tgn-m", name: "THIS is how social media will change in 2025", src: "/thumbnail-references/kallaway/onqul-tgn-m.webp", category: "Platform Trends", cue: REFERENCE_CUE },
  { id: "kallaway-lmxpbp7dd48", name: "How to Create Irresistible Hooks (and blow up your content)", src: "/thumbnail-references/kallaway/lmxpbp7dd48.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-yrqyskjqtfw", name: "I Made 367 Videos and Here's What I Discovered", src: "/thumbnail-references/kallaway/yrqyskjqtfw.webp", category: "Growth & Strategy", cue: REFERENCE_CUE },
  { id: "kallaway-ububzunpi3e", name: "How To Make 6-Figures With Content In 2025 (Full Breakdown)", src: "/thumbnail-references/kallaway/ububzunpi3e.webp", category: "Platform Trends", cue: REFERENCE_CUE },
  { id: "kallaway-ffvlkn0cski", name: "How To Make Money As A Creator From Day 1", src: "/thumbnail-references/kallaway/ffvlkn0cski.webp", category: "Creator Business", cue: REFERENCE_CUE },
  { id: "kallaway-8js_x-64jsm", name: "Social Media Expert Breaks Down $100M Content Strategy (Full Case Study)", src: "/thumbnail-references/kallaway/8js_x-64jsm.webp", category: "Creator Business", cue: REFERENCE_CUE },
  { id: "kallaway-aca1lae0mgo", name: "Do THIS To Blow Up Your Brand in 2025 (SuperUGC Strategy)", src: "/thumbnail-references/kallaway/aca1lae0mgo.webp", category: "Creator Business", cue: REFERENCE_CUE },
  { id: "kallaway-i4bes-sgzdm", name: "Social Media Is Now On 'Easy Mode' (Anyone Can Blow Up in 2025)", src: "/thumbnail-references/kallaway/i4bes-sgzdm.webp", category: "Platform Trends", cue: REFERENCE_CUE },
  { id: "kallaway-wjqpfglrscw", name: "How Steven Bartlett Built a Content Machine That Makes $25M_Year", src: "/thumbnail-references/kallaway/wjqpfglrscw.webp", category: "Creator Business", cue: REFERENCE_CUE },
  { id: "kallaway-mas69hnjxme", name: "The NEW Way to Win On Social Media in 2025", src: "/thumbnail-references/kallaway/mas69hnjxme.webp", category: "Platform Trends", cue: REFERENCE_CUE },
  { id: "kallaway-t5z-q1bg1tu", name: "How To Become A Master Storyteller", src: "/thumbnail-references/kallaway/t5z-q1bg1tu.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-iywtdykncqy", name: "How to use psychology to hack viewers brains (& make more money)", src: "/thumbnail-references/kallaway/iywtdykncqy.webp", category: "Hooks & Storytelling", cue: REFERENCE_CUE },
  { id: "kallaway-ecqb_attjug", name: "I Cracked The Social Media Algorithm (Full Formula Explained)", src: "/thumbnail-references/kallaway/ecqb_attjug.webp", category: "AI & Tools", cue: REFERENCE_CUE },
]
