/**
 * Short-Form Thumbnail Stylization Archetypes & Core Tenants
 *
 * A restrained editorial system tuned for Prometheus Studio's minimalist direction:
 * - Editorial serif display type set in bone/ivory or charcoal ink (no neon clichés)
 * - Depth separation (text behind principal speaker) with a muted, single accent
 * - A quiet photo treatment set by default: deep vignette only, decor off by default
 * - Floating assets are opt-in signatures, never the default
 */

export interface ShortFormStyleConfig {
  id: string
  name: string
  category: 'behind_speaker' | 'script_hybrid' | '3d_assets' | 'editorial_collage'
  tagline: string
  primaryFont: string
  scriptFont?: string
  defaultBrandColor: string
  secondaryColor?: string
  textLayer: 'behind' | 'foreground' | 'split'
  hasRimLight: boolean
  hasVignette: boolean
  defaultVignetteIntensity: number // 0 to 1
  hasFilmGrain: boolean
  hasFringeBlur: boolean
  hasInkBleed: boolean
  defaultFloatingAssets: string[]
  backgroundGrid: boolean
  telemetryRuler: boolean
  sampleHeadline: string
  sampleScript?: string
  sampleSubtitle?: string
}

export const SHORT_FORM_ARCHETYPES: ShortFormStyleConfig[] = [
  {
    id: 'behind_subject_blueprint',
    name: 'Masthead Behind',
    category: 'behind_speaker',
    tagline: 'Oversized editorial serif rising behind the speaker, quiet contrast',
    primaryFont: 'Georgia, "Times New Roman", serif',
    scriptFont: 'cursive',
    defaultBrandColor: '#3E5C76',
    secondaryColor: '#E8E1D2',
    textLayer: 'behind',
    hasRimLight: false,
    hasVignette: true,
    defaultVignetteIntensity: 0.5,
    hasFilmGrain: false,
    hasFringeBlur: false,
    hasInkBleed: false,
    defaultFloatingAssets: [],
    backgroundGrid: false,
    telemetryRuler: false,
    sampleHeadline: 'A QUIET MONSTER',
    sampleScript: 'so it goes',
    sampleSubtitle: 'MASTER CLASS',
  },
  {
    id: 'confessional_gold',
    name: 'Statement Portrait',
    category: 'behind_speaker',
    tagline: 'Deep charcoal field with a single bone accent and editorial subtitle',
    primaryFont: 'Georgia, "Times New Roman", serif',
    scriptFont: 'cursive',
    defaultBrandColor: '#E8E1D2',
    secondaryColor: '#2B2D33',
    textLayer: 'foreground',
    hasRimLight: false,
    hasVignette: true,
    defaultVignetteIntensity: 0.7,
    hasFilmGrain: false,
    hasFringeBlur: false,
    hasInkBleed: false,
    defaultFloatingAssets: [],
    backgroundGrid: false,
    telemetryRuler: false,
    sampleHeadline: 'STILL, I WIN',
    sampleScript: 'a field note',
    sampleSubtitle: 'ON HOLDING ON',
  },
  {
    id: 'script_sans_split',
    name: 'Script & Sans Split',
    category: 'script_hybrid',
    tagline: 'Two-column pairing: an editorial serif face against a grotesque sans',
    primaryFont: 'Georgia, "Times New Roman", serif',
    scriptFont: '"Black Delights", cursive',
    defaultBrandColor: '#3A4B38',
    secondaryColor: '#E8E1D2',
    textLayer: 'split',
    hasRimLight: false,
    hasVignette: true,
    defaultVignetteIntensity: 0.5,
    hasFilmGrain: false,
    hasFringeBlur: false,
    hasInkBleed: false,
    defaultFloatingAssets: [],
    backgroundGrid: false,
    telemetryRuler: false,
    sampleHeadline: 'WHAT IS OWED',
    sampleScript: 'the quiet part',
    sampleSubtitle: 'THE RULES OF RENAMING',
  },
  {
    id: 'paper_collage_pinup',
    name: 'Loose-Width Paper Cut',
    category: 'editorial_collage',
    tagline: 'Pinned paper note with a single doodle arrow; quiet texture',
    primaryFont: 'Georgia, "Times New Roman", serif',
    scriptFont: 'cursive',
    defaultBrandColor: '#E8E1D2',
    secondaryColor: '#2B2D33',
    textLayer: 'behind',
    hasRimLight: false,
    hasVignette: true,
    defaultVignetteIntensity: 0.55,
    hasFilmGrain: false,
    hasFringeBlur: false,
    hasInkBleed: false,
    defaultFloatingAssets: ['doodle_arrow'],
    backgroundGrid: false,
    telemetryRuler: false,
    sampleHeadline: 'PRINT THE POINT',
    sampleScript: 'from design',
    sampleSubtitle: 'CREATIVE DIRECTOR',
  },
  {
    id: 'creator_3d_icons',
    name: 'Studio Still',
    category: '3d_assets',
    tagline: 'One readable headline, a single small icon, neutral negative space',
    primaryFont: 'Georgia, "Times New Roman", serif',
    scriptFont: 'cursive',
    defaultBrandColor: '#4C6E9E',
    secondaryColor: '#E8E1D2',
    textLayer: 'behind',
    hasRimLight: false,
    hasVignette: true,
    defaultVignetteIntensity: 0.5,
    hasFilmGrain: false,
    hasFringeBlur: false,
    hasInkBleed: false,
    defaultFloatingAssets: ['camera'],
    backgroundGrid: false,
    telemetryRuler: false,
    sampleHeadline: 'MAKE IT ON PURPOSE',
    sampleScript: 'content studio',
    sampleSubtitle: 'ON THE SHOT',
  },
  {
    id: 'super_confident_script',
    name: 'Serif Overlap',
    category: 'script_hybrid',
    tagline: 'Heavy editorial serif with a single overlapping accent line',
    primaryFont: 'Georgia, "Times New Roman", serif',
    scriptFont: '"Black Delights", cursive',
    defaultBrandColor: '#2B2D33',
    secondaryColor: '#E8E1D2',
    textLayer: 'foreground',
    hasRimLight: false,
    hasVignette: true,
    defaultVignetteIntensity: 0.6,
    hasFilmGrain: false,
    hasFringeBlur: false,
    hasInkBleed: false,
    defaultFloatingAssets: [],
    backgroundGrid: false,
    telemetryRuler: false,
    sampleHeadline: 'HOLD THE CENTER',
    sampleScript: 'so be it',
    sampleSubtitle: 'WITHIN THE ROOM',
  },
  {
    id: 'torn_edge_editorial',
    name: 'Marginalia Editorial',
    category: 'editorial_collage',
    tagline: 'Cropped photo texture with a ruled margin-note strip',
    primaryFont: 'Georgia, "Times New Roman", serif',
    scriptFont: 'cursive',
    defaultBrandColor: '#77787B',
    secondaryColor: '#E8E1D2',
    textLayer: 'behind',
    hasRimLight: false,
    hasVignette: true,
    defaultVignetteIntensity: 0.5,
    hasFilmGrain: false,
    hasFringeBlur: false,
    hasInkBleed: false,
    defaultFloatingAssets: [],
    backgroundGrid: false,
    telemetryRuler: false,
    sampleHeadline: 'MARGINS NOTED',
    sampleScript: 'to the side',
    sampleSubtitle: 'STREETWEAR EDIT',
  },
  {
    id: 'mrbeast_grid_contrast',
    name: 'Grid Still',
    category: '3d_assets',
    tagline: 'Fine hairline grid, centered subject, restrained contrast',
    primaryFont: 'Georgia, "Times New Roman", serif',
    scriptFont: 'sans-serif',
    defaultBrandColor: '#3E5C76',
    secondaryColor: '#E8E1D2',
    textLayer: 'foreground',
    hasRimLight: false,
    hasVignette: true,
    defaultVignetteIntensity: 0.55,
    hasFilmGrain: false,
    hasFringeBlur: false,
    hasInkBleed: false,
    defaultFloatingAssets: [],
    backgroundGrid: false,
    telemetryRuler: false,
    sampleHeadline: 'WEEK 1',
    sampleScript: 'no shortcuts',
    sampleSubtitle: 'THE EIGHTEEN MONTHS',
  },
  {
    id: 'cmo_brain_grid',
    name: 'CMO Brain & Grid',
    category: 'behind_speaker',
    tagline: 'Dark charcoal slate with vector grid, royal cobalt chip headline, curved chalk arrow',
    primaryFont: 'Anton, "Archivo Black", sans-serif',
    defaultBrandColor: '#1D4ED8',
    secondaryColor: '#FFFFFF',
    textLayer: 'foreground',
    hasRimLight: true,
    hasVignette: true,
    defaultVignetteIntensity: 0.65,
    hasFilmGrain: true,
    hasFringeBlur: false,
    hasInkBleed: false,
    defaultFloatingAssets: ['doodle_arrow'],
    backgroundGrid: true,
    telemetryRuler: false,
    sampleHeadline: "INSIDE A CMO'S BRAIN",
    sampleScript: 'growth system',
    sampleSubtitle: 'STRATEGY BREAKDOWN',
  },
  {
    id: 'rewind_dual_rim',
    name: 'Rewind Dual-Rim',
    category: 'script_hybrid',
    tagline: 'Cyan & warm amber dual rim lighting, large script behind head, paper sticker collage',
    primaryFont: 'Anton, "Archivo Black", sans-serif',
    scriptFont: 'cursive',
    defaultBrandColor: '#00F0FF',
    secondaryColor: '#FF6B00',
    textLayer: 'behind',
    hasRimLight: true,
    hasVignette: true,
    defaultVignetteIntensity: 0.75,
    hasFilmGrain: true,
    hasFringeBlur: true,
    hasInkBleed: true,
    defaultFloatingAssets: ['doodle_arrow'],
    backgroundGrid: false,
    telemetryRuler: false,
    sampleHeadline: '2025 REWIND',
    sampleScript: 'so it goes',
    sampleSubtitle: 'BEHIND THE SCENES',
  },
  {
    id: 'tech_proof_card',
    name: 'Tech Proof Card',
    category: '3d_assets',
    tagline: 'Floating macOS balance card with green metric pill and high-arousal facial anchor',
    primaryFont: 'Anton, "Archivo Black", sans-serif',
    scriptFont: 'sans-serif',
    defaultBrandColor: '#00C853',
    secondaryColor: '#2563EB',
    textLayer: 'foreground',
    hasRimLight: true,
    hasVignette: true,
    defaultVignetteIntensity: 0.7,
    hasFilmGrain: false,
    hasFringeBlur: false,
    hasInkBleed: false,
    defaultFloatingAssets: ['dollar', 'doodle_arrow'],
    backgroundGrid: true,
    telemetryRuler: false,
    sampleHeadline: '3 WAYS TO SCALE',
    sampleScript: '$14.70k balance',
    sampleSubtitle: 'VERIFIED METRIC',
  },
  {
    id: 'metric_growth_dashboard',
    name: 'Metric Growth Dashboard',
    category: '3d_assets',
    tagline: 'Dark analytics dashboard card with +12.3M green up pills and high-pass facial clarity',
    primaryFont: 'Anton, "Archivo Black", sans-serif',
    defaultBrandColor: '#00E676',
    secondaryColor: '#E11D48',
    textLayer: 'behind',
    hasRimLight: true,
    hasVignette: true,
    defaultVignetteIntensity: 0.6,
    hasFilmGrain: false,
    hasFringeBlur: false,
    hasInkBleed: false,
    defaultFloatingAssets: ['dollar'],
    backgroundGrid: false,
    telemetryRuler: false,
    sampleHeadline: 'EASY MODE',
    sampleScript: 'now or never',
    sampleSubtitle: '12.3M VIEWS',
  },
  {
    id: 'burnout_urgency',
    name: 'Urgency & Burnout',
    category: 'editorial_collage',
    tagline: 'Desaturated exhaustion treatment with red zigzag crash arrows and calendar overlay',
    primaryFont: 'Anton, "Archivo Black", sans-serif',
    defaultBrandColor: '#DC2626',
    secondaryColor: '#FACC15',
    textLayer: 'foreground',
    hasRimLight: true,
    hasVignette: true,
    defaultVignetteIntensity: 0.8,
    hasFilmGrain: true,
    hasFringeBlur: false,
    hasInkBleed: false,
    defaultFloatingAssets: ['calendar_x', 'doodle_arrow'],
    backgroundGrid: false,
    telemetryRuler: true,
    sampleHeadline: 'TIME IS TICKING',
    sampleScript: 'too late',
    sampleSubtitle: 'CRITICAL ALERT',
  },
]
